- name: install php-fpm packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php70
    - php70-fpm
    - php70-mcrypt
    - php70-cli
    - php70-common
    - php70-devel
    - php70-mbstring
    - php70-mysqlnd
    - php70-opcache
    - php70-pdo
    - php70-pecl-apcu
    - php70-process
    - php70-xml
    - php70-gd
  notify: restart nginx
  tags:
    - php

- name: start and enable php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: yes
  tags:
    - php

- name: copy php config from template
  template:
    src: php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: copy php-fpm config
  copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
  notify: restart php-fpm
  tags:
    - php

- name: copy default setting config file from template
  template:
    src: default-php.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx
  tags:
    - php

- name: copy virthalhost config from template
  template:
    src: virtualhost-php.conf.j2
    dest: /etc/nginx/conf.d/{{ item.domain }}.conf
  with_items:
    - "{{ site | default([]) }}"
  notify: restart nginx
  tags:
    - php

- name: copy monit config for php-fpm
  copy:
    src: monit.d/php-fpm
    dest: /etc/monit.d/php-fpm
    owner: root
    group: root
    mode: 0644
  notify: restart monit
  tags:
    - php

- name: copy php-fpm log setting from template
  template:
    src: php-fpm-awslogs.conf.j2
    dest: /etc/awslogs/config/php-fpm.conf
  notify: restart awslogs agent
  when: awslogs is defined and awslogs == "enable"
  tags:
    - php

- name: copy php-fpm logrotate config
  copy:
    src: logrotate.d/php-fpm
    dest: /etc/logrotate.d/php-fpm
    owner: root
    group: root
    mode: 0644
  tags:
    - php
