---
- hosts: all
  become: yes
  roles:
    - role: amnz2
      when: 
        - "ansible_distribution == 'Amazon'"
        - "ansible_distribution_major_version == '2'"
    - role: amnz
      when: 
        - "ansible_distribution == 'Amazon'"
        - "ansible_distribution_major_version == 'NA'"      
    - role: centos
      when:
        - "ansible_distribution == 'Centos'"
        - "ansible_distribution_major_version == '7'"
    - role: redhat
      when:
        - "ansible_distribution == 'Red Hat Enterprise Linux'"
        - "ansible_distribution_major_version == '7'"
