---
- name: download WordPress
  get_url:
    url: https://ja.wordpress.org/latest-ja.zip
    dest: "{{ wp_dir }}/latest-ja.zip"
  tags:
    - wordpress

- name: extract archive
  command: /usr/bin/unzip latest-ja.zip
  args:
    chdir: "{{ wp_dir }}" 
    creates: "{{ wp_dir }}/wordpress"
  tags:
    - wordpress

- name: install mysql server
  yum:
    name: mysql56-server
    state: present
  when: mysql_host == "localhost" 
  tags:
    - wordpress

- name: start and enable to mysql
  service:
    name: mysqld
    state: started
    enabled: yes
  when: mysql_host == "localhost" 
  tags:
    - wordpress

- name: install mysql-python27
  yum:
    name: MySQL-python27
    state: present
  tags:
    - wordpress

- name: fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no
  become_method: sudo 
  tags:
    - wordpress

- name: create WordPress database
  mysql_db:
    name: "{{ wp_db_name }}"
    login_host: "{{ mysql_host }}"
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
    state: present
  when: mysql_host != "localhost" 
  tags:
    - wordpress

- name: create WordPress database
  mysql_db:
    name: "{{ wp_db_name }}"
    login_host: "{{ mysql_host }}"
    state: present
  when: mysql_host == "localhost" 
  tags:
    - wordpress

- name: create WordPress database user
  mysql_user: name={{ wp_db_user }} login_host={{ mysql_host }} login_user={{ mysql_user }} login_password={{ mysql_password }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='%' state=present
  when: mysql_host != "localhost" 
  tags:
    - wordpress

- name: create WordPress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    login_host: "{{ mysql_host }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: "{{ mysql_host }}"
    state: present
  when: mysql_host == "localhost" 
  tags:
    - wordpress

- name: copy WordPress config file
  template:
    src: wp-config.php
    dest: "{{ wp_dir }}/wordpress/"
  tags:
    - wordpress

- name: change ownership of WordPress installation
  file:
    path: "{{ wp_dir }}/wordpress/"
    owner: apache
    group: apache
    state: directory
    recurse: yes
