---
####################
# Package Install
####################
- name: install necessary packages for investigation
  yum:
    name: "{{ item }}"
  with_items:
    - dstat
    - sysstat
    - iotop
    - mlocate
    - telnet
    - htop
    - strace
    - tcpdump

- name: install other necessary packages
  yum:
    name: "{{ item }}"
  with_items:
    - epel-release
    - vim
    - wget
    - screen
    - tree
    - postfix
    - unzip
    - make
    - gcc
    - gcc-c++
    - screen
    - mailx
    - monit

- name: remove unnecessary packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - sendmail
 
- name: copy monit.conf from template
  template:
    src: monit.conf.j2
    dest: /etc/monit.conf
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify: restart monit

- name: start and enable service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - monit
    - postfix
