---
####################
# Epel Repo Install
####################
- name: install epel-release
  yum:
    name: epel-release
    state: present
    
####################
# Package Install
####################
- name: install necessary packages for investigation
  yum:
    name: "{{ item }}"
    enablerepo: epel
  with_items:
    - dstat
    - sysstat
    - iotop
    - mlocate
    - telnet
    - htop
    - strace
    - tcpdump
  failed_when: False
  
- name: install other necessary packages
  yum:
    name: "{{ item }}"
    enablerepo: epel
  with_items:
    - epel-release
    - vim
    - wget
    - screen
    - tree
    - postfix
    - unzip
    - make
    - gcc
    - gcc-c++
    - screen
    - mailx
    - monit
  failed_when: False
  
- name: remove unnecessary packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - sendmail
  failed_when: False
  
- name: copy monit.conf from template
  template:
    src: monit.conf.j2
    dest: /etc/monit.conf
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify: restart monit

- name: start and enable service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - monit
    - postfix
  failed_when: False
